# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install slmd
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install wheel
          pip install slmd

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Compile with pandoc
        run: ./compile

      - name: Install npm packages
        run: cd website && npm install
        
      - name: Test
        run: |
          pwd
          ls -la
          ls -la website
          

      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          # ftp server
          server: cp150.sp-server.net
          # ftp username
          username: github@static.hrstmnn.de
          # ftp password
          password: ${{ secrets.CPANEL_FTP }}
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftps # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: ./website/ # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: .git* # optional
